name: Coleta Diaria LoL

on:
  schedule:
    - cron: '0 5 * * *' # Roda às 02:00 AM (Horário Rio/Brasília)
  workflow_dispatch: # Botão manual

permissions:
  contents: write # Permissão vital para o bot salvar

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90 # Tempo extra para coleta grande
    
    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Rodar Script
        env:
          RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: python app.py

      - name: Salvar Dados (Auto Commit Blindado)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Bot: Novas partidas adicionadas"
          file_pattern: '*.csv'
          # Se tiver conflito, força a atualização (seguro pois queremos apenas somar dados)
          push_options: '--force'
