name: Coleta Diaria LoL

on:
  schedule:
    - cron: '0 5 * * *' # Roda às 02:00 AM (Horário Rio/Brasília)
  workflow_dispatch: # Botão manual

permissions:
  contents: write # Permissão vital para o bot salvar

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90 # Tempo extra para coleta grande
    
    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Rodar Script
        env:
          RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}
          # GCP e SHEET não são mais obrigatórios se formos 100% banco, 
          # mas deixei aqui caso vc ainda queira usar o backup no sheets.
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          # AQUI ESTAVA FALTANDO A CHAVE NOVA:
          DB_URL: ${{ secrets.DB_URL }}
        run: python app.py

      - name: Salvar Dados (Auto Commit Blindado)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Bot: Backup CSV diario"
          file_pattern: 'dados/*.csv'
          push_options: '--force'
